// START auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// END auth

// START account
export const GET_AUTHENTICATED_USER_INFO_REQUEST = 'GET_AUTHENTICATED_USER_INFO_REQUEST';
export const GET_AUTHENTICATED_USER_INFO_SUCCESS = 'GET_AUTHENTICATED_USER_INFO_SUCCESS';
export const GET_AUTHENTICATED_USER_INFO_FAILURE = 'GET_AUTHENTICATED_USER_INFO_FAILURE';

export const GET_OTHER_USER_INFO_REQUEST = 'GET_OTHER_USER_INFO_REQUEST';
export const GET_OTHER_USER_INFO_SUCCESS = 'GET_OTHER_USER_INFO_SUCCESS';
export const GET_OTHER_USER_INFO_FAILURE = 'GET_OTHER_USER_INFO_FAILURE';

export const GET_USER_FOLLOWER_LIST_REQUEST = 'GET_USER_FOLLOWER_LIST_REQUEST';
export const GET_USER_FOLLOWER_LIST_SUCCESS = 'GET_USER_FOLLOWER_LIST_SUCCESS';
export const GET_USER_FOLLOWER_LIST_FAILURE = 'GET_USER_FOLLOWER_LIST_FAILURE';

export const GET_USER_FOLLOWING_LIST_REQUEST = 'GET_USER_FOLLOWING_LIST_REQUEST';
export const GET_USER_FOLLOWING_LIST_SUCCESS = 'GET_USER_FOLLOWING_LIST_SUCCESS';
export const GET_USER_FOLLOWING_LIST_FAILURE = 'GET_USER_FOLLOWING_LIST_FAILURE';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE = 'UNFOLLOW_USER_FAILURE';

// END account

// START repository
export const GET_REPOSITORY_LIST_REQUEST = 'GET_REPOSITORY_LIST_REQUEST';
export const GET_REPOSITORY_LIST_SUCCESS = 'GET_REPOSITORY_LIST_SUCCESS';
export const GET_REPOSITORY_LIST_FAILURE = 'GET_REPOSITORY_LIST_FAILURE';

export const REPOSITORY_FILTER_BY_SEARCH = 'REPOSITORY_FILTER_BY_SEARCH';
export const CLEAR_REPOSITORY_FILTER_BY_SEARCH = 'CLEAR_REPOSITORY_FILTER_BY_SEARCH';

export const REPOSITORY_FILTER_BY_TYPE = 'REPOSITORY_FILTER_BY_TYPE';
export const CLEAR_REPOSITORY_FILTER_BY_TYPE = 'CLEAR_REPOSITORY_FILTER_BY_TYPE';

export const GET_REPOSITORY_REQUEST = 'GET_REPOSITORY_REQUEST';
export const GET_REPOSITORY_SUCCESS = 'GET_REPOSITORY_SUCCESS';
export const GET_REPOSITORY_FAILURE = 'GET_REPOSITORY_FAILURE';

export const GET_REPOSITORY_BRANCHES_REQUEST = 'GET_REPOSITORY_BRANCHES_REQUEST';
export const GET_REPOSITORY_BRANCHES_SUCCESS = 'GET_REPOSITORY_BRANCHES_SUCCESS';
export const GET_REPOSITORY_BRANCHES_FAILURE = 'GET_REPOSITORY_BRANCHES_FAILURE';

export const GET_REPOSITORY_COMMITS_REQUEST = 'GET_REPOSITORY_COMMITS_REQUEST';
export const GET_REPOSITORY_COMMITS_SUCCESS = 'GET_REPOSITORY_COMMITS_SUCCESS';
export const GET_REPOSITORY_COMMITS_FAILURE = 'GET_REPOSITORY_COMMITS_FAILURE';

export const GET_REPOSITORY_LANGUAGES_REQUEST = 'GET_REPOSITORY_LANGUAGES_REQUEST';
export const GET_REPOSITORY_LANGUAGES_SUCCESS = 'GET_REPOSITORY_LANGUAGES_SUCCESS';
export const GET_REPOSITORY_LANGUAGES_FAILURE = 'GET_REPOSITORY_LANGUAGES_FAILURE';

// END repository

// START activity
export const GET_USER_PUBLIC_EVENTS_REQUEST = 'GET_USER_PUBLIC_EVENTS_REQUEST';
export const GET_USER_PUBLIC_EVENTS_FAILURE = 'GET_USER_PUBLIC_EVENTS_FAILURE';
export const GET_USER_PUBLIC_EVENTS_SUCCESS = 'GET_USER_PUBLIC_EVENTS_SUCCESS';

// END activity
