// START auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// END auth

// START account
export const GET_AUTHENTICATED_USER_INFO_REQUEST = 'GET_AUTHENTICATED_USER_INFO_REQUEST';
export const GET_AUTHENTICATED_USER_INFO_SUCCESS = 'GET_AUTHENTICATED_USER_INFO_SUCCESS';
export const GET_AUTHENTICATED_USER_INFO_FAILURE = 'GET_AUTHENTICATED_USER_INFO_FAILURE';

// END account

// START repository
export const GET_REPOSITORY_LIST_REQUEST = 'GET_REPOSITORY_LIST_REQUEST';
export const GET_REPOSITORY_LIST_SUCCESS = 'GET_REPOSITORY_LIST_SUCCESS';
export const GET_REPOSITORY_LIST_FAILURE = 'GET_REPOSITORY_LIST_FAILURE';

export const REPOSITORY_FILTER = 'REPOSITORY_FILTER';
export const CLEAR_REPOSITORY_FILTER = 'CLEAR_REPOSITORY_FILTER';

// END repository

// START activity
export const GET_USER_PUBLIC_EVENTS_REQUEST = 'GET_USER_PUBLIC_EVENTS_REQUEST';
export const GET_USER_PUBLIC_EVENTS_FAILURE = 'GET_USER_PUBLIC_EVENTS_FAILURE';
export const GET_USER_PUBLIC_EVENTS_SUCCESS = 'GET_USER_PUBLIC_EVENTS_SUCCESS';

// END activity
